#!/usr/bin/env bash

## Autostart Programs
exec swaybg -i ~/.config/river/bg.jpg &

# Fix Java GUI on Wayland
export GDK_BACKEND=wayland,x11
export _JAVA_AWT_WM_NONREPARENTING=1

# Kill already running processes
_ps=(waybar mako)
for _prs in "${_ps[@]}"; do
	if [[ $(pidof ${_prs}) ]]; then
		killall -9 ${_prs}
	fi
done

if ! pgrep -x "polkit-gnome-authentication-agent-1" >/dev/null; then
	/usr/libexec/polkit-gnome-authentication-agent-1 &
fi

# Set wallpaper
# ~/.config/river/scripts/wallpaper &

# Set resolution
wlr-randr --output Virtual-1 --mode 1920x1080@60 &

# Launch notification daemon (mako)
~/.config/river/scripts/notifications &

# Launch statusbar (waybar)
~/.config/river/scripts/statusbar &
