#!/usr/bin/env bash

## Autostart Programs

# Kill already running process
_ps=(waybar mako)
for _prs in "${_ps[@]}"; do
	if [[ `pidof ${_prs}` ]]; then
		killall -9 ${_prs}
	fi
done

if ! pgrep -x "polkit-gnome-authentication-agent-1" >/dev/null; then
    /usr/libexec/polkit-gnome-authentication-agent-1 &
fi

riverctl spawn "dbus-update-activation-environment SEATD_SOCK DISPLAY WAYLAND _DISPLAY XDG_CURRENT_DESKTOP=river"
q
# Set wallpaper

# Apply themes
~/.config/river/scripts/gtkthemes &

# Lauch notification daemon (mako)
~/.config/river/scripts/notifications &

# Lauch statusbar (waybar)
~/.config/river/scripts/statusbar &

# Start network manager applet
nm-applet --indicator &
