#!/bin/sh

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked; do
  # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
  riverctl map Supere None XF86AudioRaiseVolume spawn '$HOME/.config/river/scripts/volume --inc'
  riverctl map Supere None XF86AudioLowerVolume spawn '$HOME/.config/river/scripts/volume --dec'
  riverctl map Supere None XF86AudioMute spawn '$HOME/.config/river/scripts/volume --toggle'

  # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
  riverctl map Supere None XF86AudioMedia spawn 'playerctl play-pause'
  riverctl map Supere None XF86AudioPlay spawn 'playerctl play-pause'
  riverctl map Supere None XF86AudioPrev spawn 'playerctl previous'
  riverctl map Supere None XF86AudioNext spawn 'playerctl next'

  # Control screen backlight brightness with light (https://gitlab.com/dpeukert/light)
  riverctl map Supere None XF86MonBrightnessUp spawn '$HOME/.config/river/scripts/brightness --inc'
  riverctl map Supere None XF86MonBrightnessDown spawn '$HOME/.config/river/scripts/brightness --dec'
done

# Mod+J and Mod+K to focus the next/previous view in the layout stack
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

# Mod+Shift+J and Mod+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

# Mod+Period and Mod+Comma to focus the next/previous output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

# Mod+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

# Mod+Return to bump the focused view to the top of the layout stack
# riverctl map normal Super Return zoom

# Mod+H and Mod+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

# Mod+Shift+H and Mod+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

# Mod+Alt+{H,J,K,L} to move views
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal  Super+Alt K move up 100
riverctl map normal  Super+Alt L move right 100

# Mod+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal  Super+Alt+Control H snap left
riverctl map normal  Super+Alt+Control J snap down
riverctl map normal  Super+Alt+Control K snap up
riverctl map normal  Super+Alt+Control L snap right

# Mod+Alt+Shif+{H,J,K,L} to resize views
riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100
riverctl map normal Super+Alt+Shift L resize horizontal 100

# Mod + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Mod + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Mod+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Mod+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Mod+Ctrl+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Mod+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Mod+0 to focus all tags
# Mod+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Mod+Space to toggle float
riverctl map normal Super Space toggle-float

# Super+Return to start an instance of alacritty
#riverctl map normal Super Return spawn '$HOME/.config/river/scripts/foot'
#riverctl map normal Super+Shift Return spawn '$HOME/.config/river/scripts/foot -f'
riverctl map normal Super Return spawn '$HOME/.config/river/scripts/alacritty'
riverctl map normal Super+Shift Return spawn '$HOME/.config/river/scripts/alacritty -f'

# Super+W to close the focused view
riverctl map normal Super Q close

riverctl map normal Super e spawn "thunar"

riverctl map normal Super b spawn "flatpak run app.zen_browser.zen"


# reload
riverctl map normal Super R spawn $HOME/.config/river/init

riverctl map normal Super Q close

# Super+Alt+Q to exit river
riverctl map normal Super+Alt Q exit


# Super+Shift+F to toggle float
riverctl map normal Super+Shift F toggle-float

# Super+F to toggle fullscreen
riverctl map normal Super F toggle-fullscreen

# Super+D to spawn rofi drun
riverctl map normal Super D spawn '$HOME/.config/river/scripts/wofi_menu'


# Super+v to open clipboard
riverctl map normal Super v spawn 'cliphist list | rofi -dmenu -p Clipboard | cliphist decode | wl-copy'

# Super+Shift+C to clear clipboard
#riverctl map normal Super+Shift C spawn 'cliphist wipe'
riverctl map normal None Print spawn 'IMG=~/Pictures/screenshots/$(date | sed "s/\s/-/g" | sed "s/--/-/g").png&&grim -g "$(slurp)" $IMG && cat $IMG | wl-copy && notify-send "Screenshot has been saved and copied to your clipboard" -a "grim" -u normal -t 2000'

# Print to take screenshot

# Super+P to open dmenu_power
riverctl map normal Super X spawn '$HOME/.config/river/scripts/wofi_powermenu'

# Super+S to open dmenu_mager
#riverctl map normal Super S spawn dmenu_mager

# Super+Tab to open list window
#riverctl map normal Super Tab spawn 'rofi -show window'
